### ISSUE TITLE
Cannot get the SQL query generated

### ISSUE THREAD

**Issue by Luigi6821** [axelheer/nein-linq#41]
Hi, 
I am using nein-linq with EF 6.4.4 (net standard).
Maybe I am not using library in the right way but when I try to debug the generated SQL I get
![image](https://github.com/axelheer/nein-linq/assets/53300194/bc3e964a-3c47-48ac-8465-fb544cd1cb30)
The simple query is defined as follows:

`dbContext.Set<ADDRESS>().ToInjectable().Select(a => a.ALPHACODE.LimitText(10));`

The LimitText method is defined in a static class as follows:

```
public static class AMOSFunctionsGeneric
{
    [InjectLambda]
    public static string LimitText(this string value, int maxLength)
    {
        if (value != null && value.Length > maxLength)
            return value.Substring(0, maxLength);
        return value;
    }

    public static Expression<Func<string, int, string>> LimitText()
    {
        return (v, l) => v != null && v.Length > l ? v.Substring(0, l) : v;
    }
}
```

Is there a way to preview the generated SQL ?
PS: if I use Database.Log event I can get the generated sql but is important to have it in VS debug.

**Comment by axelheer** [comment]
I have to look into that, may take a while...

**Comment by axelheer** [comment]
The problem is, that the "SQL Debug Property" does not use the actual LINQ Query Provider. Thus, it goes round NeinLinq's rewrite mechanism, which actually applies right before query execution...

You can apply this stuff manually for debugging purpose:

`var debug = ((RewriteQueryProvider)query.Provider).RewriteQuery(query.Expression);`

But I'll check, if I can provide this in a much nicer way...

**Comment by axelheer** [comment]
Can you check #43 if that helps?
